import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import FileUpload from '../components/FileUpload';
import { useState } from "react";
import { LogEntry } from "@/utils/file-reader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [logEntries, setLogEntries] = useState<LogEntry[]>([]);
  const [errors, setErrors] = useState<string[]>([]);


  const handleFileSelect = async (file: File, logEntries: LogEntry[], errors: string[]) => {
    console.log('Selected file:', file);
    setSelectedFile(file);
    setLogEntries(logEntries);
    setErrors(errors);

    console.debug('Log entries:', logEntries);
    console.debug('Errors:', errors);
  };

  return (
    <>
      <Head>
        <title>Web Analytic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <FileUpload onFileSelect={handleFileSelect} />
        </main>
      </div>
    </>
  );
}
